//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.29 at 04:24:55 PM CST 
//


package com.mitlab.workflow.descriptor;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActionDescriptor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActionDescriptor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="meta" type="{http://www.mitlab.org/workflow}MetaDescriptor" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="conditions" type="{http://www.mitlab.org/workflow}ConditionsDescriptor" minOccurs="0"/>
 *         &lt;element name="pre-functions" type="{http://www.mitlab.org/workflow}FunctionsDescriptor" minOccurs="0"/>
 *         &lt;element name="results" type="{http://www.mitlab.org/workflow}ResultsDescriptor"/>
 *         &lt;element name="post-functions" type="{http://www.mitlab.org/workflow}FunctionsDescriptor" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionDescriptor", propOrder = {
    "meta",
    "conditions",
    "preFunctions",
    "results",
    "postFunctions"
})
public class ActionDescriptor {

    protected List<MetaDescriptor> meta;
    protected ConditionsDescriptor conditions;
    @XmlElement(name = "pre-functions")
    protected FunctionsDescriptor preFunctions;
    @XmlElement(required = true)
    protected ResultsDescriptor results;
    @XmlElement(name = "post-functions")
    protected FunctionsDescriptor postFunctions;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the meta property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meta property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeta().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetaDescriptor }
     * 
     * 
     */
    public List<MetaDescriptor> getMeta() {
        if (meta == null) {
            meta = new ArrayList<MetaDescriptor>();
        }
        return this.meta;
    }

    /**
     * Gets the value of the conditions property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionsDescriptor }
     *     
     */
    public ConditionsDescriptor getConditions() {
        return conditions;
    }

    /**
     * Sets the value of the conditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionsDescriptor }
     *     
     */
    public void setConditions(ConditionsDescriptor value) {
        this.conditions = value;
    }

    /**
     * Gets the value of the preFunctions property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionsDescriptor }
     *     
     */
    public FunctionsDescriptor getPreFunctions() {
        return preFunctions;
    }

    /**
     * Sets the value of the preFunctions property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionsDescriptor }
     *     
     */
    public void setPreFunctions(FunctionsDescriptor value) {
        this.preFunctions = value;
    }

    /**
     * Gets the value of the results property.
     * 
     * @return
     *     possible object is
     *     {@link ResultsDescriptor }
     *     
     */
    public ResultsDescriptor getResults() {
        return results;
    }

    /**
     * Sets the value of the results property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultsDescriptor }
     *     
     */
    public void setResults(ResultsDescriptor value) {
        this.results = value;
    }

    /**
     * Gets the value of the postFunctions property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionsDescriptor }
     *     
     */
    public FunctionsDescriptor getPostFunctions() {
        return postFunctions;
    }

    /**
     * Sets the value of the postFunctions property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionsDescriptor }
     *     
     */
    public void setPostFunctions(FunctionsDescriptor value) {
        this.postFunctions = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
