//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.29 at 04:24:55 PM CST 
//


package com.mitlab.workflow.descriptor;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mitlab.workflow.descriptor package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Workflow_QNAME = new QName("http://www.mitlab.org/workflow", "workflow");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mitlab.workflow.descriptor
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WorkflowDescriptor }
     * 
     */
    public WorkflowDescriptor createWorkflowDescriptor() {
        return new WorkflowDescriptor();
    }

    /**
     * Create an instance of {@link ActionsDescriptor }
     * 
     */
    public ActionsDescriptor createActionsDescriptor() {
        return new ActionsDescriptor();
    }

    /**
     * Create an instance of {@link ConditionDescriptor }
     * 
     */
    public ConditionDescriptor createConditionDescriptor() {
        return new ConditionDescriptor();
    }

    /**
     * Create an instance of {@link ResultsDescriptor }
     * 
     */
    public ResultsDescriptor createResultsDescriptor() {
        return new ResultsDescriptor();
    }

    /**
     * Create an instance of {@link ArgDescriptor }
     * 
     */
    public ArgDescriptor createArgDescriptor() {
        return new ArgDescriptor();
    }

    /**
     * Create an instance of {@link FunctionDescriptor }
     * 
     */
    public FunctionDescriptor createFunctionDescriptor() {
        return new FunctionDescriptor();
    }

    /**
     * Create an instance of {@link MetaDescriptor }
     * 
     */
    public MetaDescriptor createMetaDescriptor() {
        return new MetaDescriptor();
    }

    /**
     * Create an instance of {@link ResultDescriptor }
     * 
     */
    public ResultDescriptor createResultDescriptor() {
        return new ResultDescriptor();
    }

    /**
     * Create an instance of {@link ConditionsDescriptor }
     * 
     */
    public ConditionsDescriptor createConditionsDescriptor() {
        return new ConditionsDescriptor();
    }

    /**
     * Create an instance of {@link ActionDescriptor }
     * 
     */
    public ActionDescriptor createActionDescriptor() {
        return new ActionDescriptor();
    }

    /**
     * Create an instance of {@link StepDescriptor }
     * 
     */
    public StepDescriptor createStepDescriptor() {
        return new StepDescriptor();
    }

    /**
     * Create an instance of {@link FunctionsDescriptor }
     * 
     */
    public FunctionsDescriptor createFunctionsDescriptor() {
        return new FunctionsDescriptor();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkflowDescriptor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mitlab.org/workflow", name = "workflow")
    public JAXBElement<WorkflowDescriptor> createWorkflow(WorkflowDescriptor value) {
        return new JAXBElement<WorkflowDescriptor>(_Workflow_QNAME, WorkflowDescriptor.class, null, value);
    }

}
